#!/usr/bin/env python3
"""Run mygame's existing feature validators without changing their assertions."""
from __future__ import annotations

import argparse
from collections import Counter
from concurrent.futures import ThreadPoolExecutor, as_completed
from contextlib import contextmanager
from dataclasses import dataclass, replace
import hashlib
import json
import math
import os
from pathlib import Path
import queue
import re
import shlex
import shutil
import signal
import subprocess
import sys
import tempfile
from threading import Event
import time

try:
    import fcntl
except ImportError:
    fcntl = None

PROJECT = Path(__file__).resolve().parents[1]
CONFIG_PATH = Path("tests/validation/suite.json")
BENCHMARK_ROOT = Path("tests/benchmarks")
GODOT_MODES = {"script", "scene", "editor", "case"}
RUNNABLE = GODOT_MODES | {"python"}
DEFAULT_TIMEOUT = 90
LOG_LIMIT_BYTES = 64 * 1024 * 1024
# Keep the historical ownership marker so saved reports remain recognizable.
REPORT_IGNORE = "# Generated by run_tests.py; this directory contains disposable test output.\n*\n"
SNAPSHOT_DIRS = {".godot", "assets", "addons", "features", "scenes", "tools", "tests", "architecture", "demo", "performance"}
SNAPSHOT_SUFFIXES = {".godot", ".cfg", ".gd", ".tscn", ".tres", ".md", ".svg", ".png", ".import", ".py", ".json"}
EXCLUDED = {".git", ".hermes", ".claude", ".env", ".mcp.json", "opencode.json", "tui.json", "credentials.json", "auth.json", "token.json", "__pycache__", "test-results", ".test-results"}
ANSI = re.compile(r"\x1b\[[0-9;]*[A-Za-z]")
ERROR_LINE = re.compile(r"^(?:(?:SCRIPT |USER )?ERROR:|FAIL(?:ED)?(?:\s|:|$)|[A-Z][A-Z0-9_]*_FAIL(?:ED)?\b|\[FAIL\]|Traceback \(most recent call last\):)")


@dataclass(frozen=True)
class Test:
    path: str
    mode: str
    entrypoint: str
    timeout: float = DEFAULT_TIMEOUT
    serial: bool = False
    reason: str = ""
    editor_plugins: bool = True

    @property
    def benchmark(self) -> bool:
        return Path(self.path).is_relative_to(BENCHMARK_ROOT)


class Console:
    COLORS = {"passed": "32", "failed": "31", "timeout": "33", "blocked": "35", "interrupted": "33"}

    def __init__(self, color: bool):
        self.color = color

    def paint(self, text: str, code: str) -> str:
        return f"\033[{code}m{text}\033[0m" if self.color else text

    def title(self, benchmarks: bool = False):
        label = "BENCHMARKS" if benchmarks else "VALIDATION"
        print("\n" + self.paint(f"  MYGAME  /  {label}", "1;36"))

    def result(self, index: int, total: int, row: dict):
        label = Path(row["path"]).stem.removeprefix("validate_").replace("_", " ").capitalize()
        width = max(24, min(66, shutil.get_terminal_size((100, 24)).columns - 34))
        label = label if len(label) <= width else label[:width - 1] + "…"
        status = self.paint(f"{row['status'].upper():11}", self.COLORS.get(row["status"], "37"))
        elapsed = f"{row['seconds']:6.1f}s" if "seconds" in row else "      —"
        print(f"  {index:3}/{total:<3}  {status} {label:{width}} {elapsed}", flush=True)

    def summary(self, counts: dict, elapsed: float, complete: bool):
        print("\n  " + self.paint("─" * 66, "2"))
        print("  " + "   ".join(self.paint(f"{counts.get(status, 0)} {status}", color)
                                  for status, color in self.COLORS.items() if status in counts))
        print(f"  {'Finished' if complete else 'INCOMPLETE'} in {elapsed:.1f}s. Logs contain the full test output.")


def copy_file(source, destination):
    """Copy-on-write where supported; never hard-link writable project files."""
    if fcntl is not None and hasattr(fcntl, "FICLONE"):
        try:
            with open(source, "rb") as reader, open(destination, "wb") as writer:
                fcntl.ioctl(writer.fileno(), fcntl.FICLONE, reader.fileno())
            shutil.copystat(source, destination)
            return destination
        except OSError:
            pass
    return shutil.copy2(source, destination)


def copy_project(source: Path, destination: Path) -> None:
    destination.mkdir()
    def ignore(_directory, names):
        return [name for name in names if name in EXCLUDED or name.startswith(".env.")]
    for path in source.iterdir():
        if path.name in EXCLUDED or path.name.startswith(".env."):
            continue
        target = destination / path.name
        if path.is_dir() and path.name in SNAPSHOT_DIRS:
            shutil.copytree(path, target, copy_function=copy_file, ignore=ignore)
        elif path.is_file() and path.suffix in SNAPSHOT_SUFFIXES:
            copy_file(path, target)


@contextmanager
def editor_plugin_settings(test: Test, project: Path):
    if test.editor_plugins:
        yield
        return
    # Only the disposable worker is changed. Godot reads later assignments last;
    # override.cfg cannot do this because the native editor ignores that file.
    settings = project / "project.godot"
    original = settings.read_bytes()
    try:
        settings.write_bytes(original + b"\n\n[editor_plugins]\nenabled=PackedStringArray()\n")
        yield
    finally:
        # Workers are reused: restore exact bytes even after failed startup,
        # cancellation, timeout, or an editor saving its project settings.
        settings.write_bytes(original)


def command_for(test: Test, project: Path, folder: Path, godot: str) -> list[str]:
    if test.mode == "python":
        return [sys.executable, str(project / test.entrypoint)]
    command = [godot, "--headless", "--path", str(project), "--log-file", str(folder / "engine.log")]
    if test.mode == "editor":
        command.append("--editor")
    if test.mode == "case":
        command.extend(["--scene", "res://tests/validation/test_host.tscn", "--", "res://" + test.entrypoint])
    else:
        # Editor tool scenes keep Godot's native editor startup and teardown.
        scene_entry = test.mode == "scene" or (test.mode == "editor" and test.entrypoint.endswith(".tscn"))
        command.extend(["--scene" if scene_entry else "--script", "res://" + test.entrypoint])
    return command


def run_test(test: Test, project: Path, report_dir: Path, godot: str, cancelled: Event) -> dict:
    identifier = Path(test.path).stem + "-" + hashlib.sha256(test.path.encode()).hexdigest()[:10]
    source_hash = hashlib.sha256((project / test.path).read_bytes()).hexdigest()
    folder = report_dir / "logs" / identifier
    folder.mkdir(parents=True)
    log = folder / "output.log"
    command = command_for(test, project, folder, godot)
    environment = os.environ.copy()
    environment.update({"XDG_DATA_HOME": str(folder / "data"),
                        "XDG_CONFIG_HOME": str(folder / "config"),
                        "XDG_CACHE_HOME": str(folder / "cache"),
                        "PYTHONUNBUFFERED": "1"})
    started = time.monotonic()
    stopped = None
    process = None
    code = None
    with editor_plugin_settings(test, project), log.open("wb") as output:
        try:
            process = subprocess.Popen(command, cwd=project, env=environment, stdout=output,
                                       stderr=subprocess.STDOUT, start_new_session=True)
            script_error = False
            carry = ""
            with log.open(errors="replace") as monitor:
                while process.poll() is None:
                    elapsed = time.monotonic() - started
                    chunk = carry + monitor.read(1024 * 1024)
                    script_error |= "SCRIPT ERROR:" in ANSI.sub("", chunk)
                    carry = chunk[-64:]
                    if cancelled.is_set():
                        stopped = "interrupted"
                    elif elapsed >= test.timeout:
                        stopped = "timeout"
                    elif log.stat().st_size >= LOG_LIMIT_BYTES:
                        stopped = "log_limit"
                    elif script_error and elapsed >= 3:
                        stopped = "script_error"
                    if stopped:
                        break
                    time.sleep(0.05)
        except OSError as error:
            output.write(str(error).encode())
            stopped = "launch_error"
        finally:
            if process is not None:
                stop_process(process)
                code = process.returncode
    # A fast producer can finish between monitor polls; never certify its
    # oversized final output as a pass just because it has already exited.
    if stopped is None and log.stat().st_size >= LOG_LIMIT_BYTES:
        stopped = "log_limit"
    errors, error_count = scan_log(log)
    finished = time.monotonic()
    status = "passed" if code == 0 and not error_count and stopped is None else "failed"
    if stopped == "timeout":
        status = "timeout"
    elif stopped == "launch_error":
        status = "blocked"
    elif stopped == "interrupted":
        status = "interrupted"
    return {"path": test.path, "mode": test.mode, "editor_plugins": test.editor_plugins,
            "status": status, "stop_reason": stopped,
            "exit_code": code, "seconds": round(finished - started, 3),
            "started_monotonic": started, "finished_monotonic": finished,
            "serial": test.serial, "timeout_seconds": test.timeout,
            "source_sha256": source_hash,
            "errors": errors, "error_count": error_count,
            "command": command, "log": log.relative_to(report_dir).as_posix()}


def stop_process(process: subprocess.Popen) -> None:
    def send(sig):
        try:
            if os.name == "posix":
                os.killpg(process.pid, sig)
            elif process.poll() is None:
                process.kill() if sig == signal.SIGKILL else process.terminate()
        except ProcessLookupError:
            pass
    send(signal.SIGTERM)
    deadline = time.monotonic() + 2
    while time.monotonic() < deadline:
        process.poll()  # Reap the leader without cutting short its children's grace period.
        try:
            if os.name == "posix":
                os.killpg(process.pid, 0)
            elif process.returncode is not None:
                break
        except ProcessLookupError:
            break
        time.sleep(0.02)
    # Wait for the whole group, not only its leader: nested runners need time
    # to cancel their own separately sessioned validators before being killed.
    send(signal.SIGKILL)
    process.wait()


def scan_log(path: Path) -> tuple[list[str], int]:
    errors = []
    count = 0
    with path.open(errors="replace") as lines:
        for line in lines:
            line = ANSI.sub("", line).strip()
            if ERROR_LINE.match(line):
                count += 1
                if len(errors) < 8:
                    errors.append(line[:1000])
    return errors, count


def execute_tests(project, tests, report_dir, godot, jobs, cancelled, record):
    parallel = [test for test in tests if not test.serial]
    serial = [test for test in tests if test.serial]
    workers = min(jobs, len(parallel) or 1)
    print(f"  Preparing {workers} isolated workspace(s)…", flush=True)
    with tempfile.TemporaryDirectory(prefix="mygame-tests-") as temporary:
        snapshot = Path(temporary) / "worker-0"
        copy_project(project, snapshot)
        available = queue.Queue()
        available.put(snapshot)
        for index in range(1, workers):
            destination = Path(temporary) / f"worker-{index}"
            copy_project(snapshot, destination)
            available.put(destination)

        def execute(test):
            if cancelled.is_set():
                return {"path": test.path, "mode": test.mode, "status": "interrupted", "reason": "Not started: run cancelled"}
            if test.mode not in RUNNABLE:
                return {"path": test.path, "mode": test.mode, "status": "blocked",
                        "reason": "Configure this test's launch mode in tests/validation/suite.json"}
            workspace = available.get()
            try:
                return run_test(test, workspace, report_dir, godot, cancelled)
            except OSError as error:
                return {"path": test.path, "mode": test.mode, "status": "blocked", "reason": str(error)}
            finally:
                available.put(workspace)

        with ThreadPoolExecutor(max_workers=workers) as pool:
            for future in as_completed([pool.submit(execute, test) for test in parallel]):
                record(future.result())
        for test in serial:
            record(execute(test))


def write_json(path: Path, data: dict) -> None:
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text(json.dumps(data, indent=2) + "\n")
    temporary.replace(path)


def render_report(path: Path, report: dict) -> None:
    template = (Path(__file__).resolve().parent / "validation/report_template.html").read_text()
    if template.count("__TEST_REPORT_JSON__") != 1:
        raise ValueError("Report template must contain exactly one __TEST_REPORT_JSON__ placeholder")
    payload = json.dumps(report).replace("<", "\\u003c").replace("&", "\\u0026")
    temporary = path.with_suffix(".html.tmp")
    temporary.write_text(template.replace("__TEST_REPORT_JSON__", payload))
    temporary.replace(path)


def run_metadata(project: Path, godot: str, uses_godot: bool) -> dict:
    metadata: dict[str, str | None] = {"runner_sha256": hashlib.sha256(Path(__file__).read_bytes()).hexdigest()}
    commands = {"source_commit": ["git", "rev-parse", "HEAD"]}
    if uses_godot:
        commands["godot_version"] = [godot, "--version"]
    for key, command in commands.items():
        try:
            result = subprocess.run(command, cwd=project, capture_output=True, text=True, timeout=5)
            metadata[key] = result.stdout.strip()[:512] if result.returncode == 0 else None
        except (OSError, subprocess.TimeoutExpired):
            metadata[key] = None
    return metadata


def load_audit(project: Path) -> tuple[dict, str | None]:
    path = project / "tests/validation/audit.json"
    if not path.exists():
        return {}, None
    try:
        data = json.loads(path.read_text())
        if not isinstance(data, dict) or not isinstance(data.get("records"), list):
            raise ValueError("expected a records array")
        records = data["records"]
        if any(not isinstance(row, dict) or not isinstance(row.get("path"), str) for row in records):
            raise ValueError("each audit record needs a path")
        if len({row["path"] for row in records}) != len(records):
            raise ValueError("duplicate audit paths")
        return {row["path"]: {**row, "reviewed_at": data.get("reviewed_at", "Date not recorded")}
                for row in records}, None
    except (ValueError, OSError) as error:
        return {}, f"Audit notes unavailable: {error}"


@contextmanager
def report_output(directory: Path, replace_existing: bool):
    """Own one output directory; never replace another writer or unrelated data."""
    if any(path.is_symlink() for path in (directory, *directory.parents)):
        raise ValueError(f"Report directory must not use a symlink: {directory}")
    directory.mkdir(parents=True, exist_ok=True)
    ignore = directory / ".gitignore"
    owned = ignore.is_file() and ignore.read_text() == REPORT_IGNORE
    if any(directory.iterdir()) and not (replace_existing and owned):
        raise ValueError(f"Report directory is not empty or not runner-owned: {directory}")
    lock_path = directory / ".run.lock"
    if lock_path.is_symlink():
        raise ValueError(f"Report lock must not be a symlink: {lock_path}")
    # Keep this inode in place while clearing the other files. Deleting the
    # directory or lock would let another writer lock a different inode.
    with lock_path.open("a+b") as lock:
        try:
            if fcntl is not None:
                fcntl.flock(lock, fcntl.LOCK_EX | fcntl.LOCK_NB)
            elif sys.platform == "win32":
                import msvcrt
                if lock.tell() == 0:
                    lock.write(b"\0")
                    lock.flush()
                lock.seek(0)
                msvcrt.locking(lock.fileno(), msvcrt.LK_NBLCK, 1)
            else:
                raise ValueError("This platform has no supported file lock for test reports")
        except OSError as error:
            raise ValueError(f"Another test run is already writing {directory}") from error
        if replace_existing:
            for path in directory.iterdir():
                if path == lock_path:
                    continue
                if path.is_dir() and not path.is_symlink():
                    shutil.rmtree(path)
                else:
                    path.unlink()
        ignore.write_text(REPORT_IGNORE)
        (directory / ".gdignore").touch()
        yield


def report_root(project: Path, benchmarks: bool = False) -> Path:
    return project / (".test-results/benchmarks" if benchmarks else ".test-results/validation")


def run_suite(project: Path, tests: list[Test], report_dir: Path, godot: str, scope: dict, jobs: int, console: Console) -> int:
    latest_dir = report_root(project, benchmarks=scope.get("suite") == "benchmarks")
    if latest_dir.is_symlink():
        raise ValueError(f"Test output root must not be a symlink: {latest_dir}")
    latest_dir.mkdir(parents=True, exist_ok=True)
    (latest_dir / ".gitignore").write_text(REPORT_IGNORE)
    (latest_dir / ".gdignore").touch()
    started = time.monotonic()
    started_at = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
    metadata = run_metadata(project, godot, any(test.mode in GODOT_MODES for test in tests))
    audit, audit_warning = load_audit(project)
    if audit_warning:
        print(f"  WARNING: {audit_warning}", flush=True)
    for entry in scope["non_tests"]:
        if entry["path"] in audit:
            entry["audit"] = audit[entry["path"]]
    results = []
    cancelled = Event()
    interrupted_signal = 0
    complete = False

    def request_stop(sig, _frame):
        nonlocal interrupted_signal
        interrupted_signal = sig
        cancelled.set()

    def save_report():
        report = {**metadata, "project": str(project), "started_at": started_at,
                  "duration_seconds": round(time.monotonic() - started, 3),
                  "complete": complete and not cancelled.is_set(), "scope": scope,
                  "audit_warning": audit_warning,
                  "counts": dict(Counter(result["status"] for result in results)),
                  "results": sorted(results, key=lambda row: row["path"])}
        write_json(report_dir / "report.json", report)
        render_report(report_dir / "index.html", report)

    def record(result):
        if result["path"] in audit:
            note = dict(audit[result["path"]])
            if note.get("source_sha256") and result.get("source_sha256"):
                note["source_changed"] = note["source_sha256"] != result["source_sha256"]
            result["audit"] = note
        if result.get("command"):
            result["command_text"] = shlex.join(result["command"])
        result["rerun_command"] = shlex.join([sys.executable, str(Path(__file__).resolve()),
                                               "--project", str(project),
                                               *(["--benchmarks"] if scope.get("suite") == "benchmarks" else []),
                                               "--filter", result["path"], "--godot", godot])
        results.append(result)
        with (report_dir / "results.jsonl").open("a") as journal:
            journal.write(json.dumps(result) + "\n")
            journal.flush()
            os.fsync(journal.fileno())
        save_report()
        console.result(len(results), len(tests), result)

    handlers = {sig: signal.signal(sig, request_stop) for sig in (signal.SIGINT, signal.SIGTERM)}
    try:
        save_report()
        execute_tests(project, tests, report_dir, godot, jobs, cancelled, record)
        assert {result["path"] for result in results} == {test.path for test in tests}
        assert len(results) == len(tests)
        complete = True
    finally:
        try:
            save_report()
            write_json(latest_dir / "latest.json", {"report": str(report_dir / "report.json")})
        finally:
            for sig, handler in handlers.items():
                signal.signal(sig, handler)
    counts = dict(Counter(result["status"] for result in results))
    console.summary(counts, time.monotonic() - started, complete and not cancelled.is_set())
    print(f"  Report: {report_dir / 'index.html'}")
    print(f"  Data:   {report_dir / 'report.json'}")
    if interrupted_signal:
        return 128 + interrupted_signal
    return 0 if all(result["status"] == "passed" for result in results) else 1


def relative_path(value: str) -> Path:
    if not isinstance(value, str) or not value or "\\" in value:
        raise ValueError(f"Expected a project-relative POSIX path: {value!r}")
    path = Path(value)
    if path.is_absolute() or any(part in (".", "..", "") for part in value.split("/")):
        raise ValueError(f"Expected a project-relative POSIX path: {value!r}")
    return path


def positive_seconds(value) -> float:
    if isinstance(value, bool):
        raise ValueError("Timeout must be a number, not a boolean")
    try:
        result = float(value)
    except (TypeError, ValueError) as error:
        raise ValueError("Timeout must be a finite positive number of seconds") from error
    if not math.isfinite(result) or result <= 0:
        raise ValueError("Timeout must be a finite positive number of seconds")
    return result


def worker_count(value) -> int:
    if isinstance(value, (bool, float)):
        raise ValueError("Worker count must be an integer")
    result = int(value)
    if result < 1 or result > 16:
        raise ValueError("Worker count must be between 1 and 16")
    return result


def previous_failures(project: Path, argument: str, benchmarks: bool = False) -> set[str]:
    if argument:
        path = Path(argument)
    else:
        pointer = json.loads((report_root(project, benchmarks) / "latest.json").read_text())
        if not isinstance(pointer, dict) or not isinstance(pointer.get("report"), str):
            raise ValueError("Invalid latest-report pointer; supply --rerun-failed REPORT explicitly")
        path = Path(pointer["report"])
    report = json.loads(path.read_text())
    if not isinstance(report, dict):
        raise ValueError(f"Not a test-runner report: {path}")
    rows = report.get("results")
    if not isinstance(rows, list) or any(not isinstance(row, dict) or not isinstance(row.get("path"), str) or not isinstance(row.get("status"), str) for row in rows):
        raise ValueError(f"Not a test-runner report: {path}")
    scope = report.get("scope", {})
    if not isinstance(scope, dict) or not isinstance(scope.get("paths", []), list):
        raise ValueError(f"Invalid scope in report: {path}")
    for name in [row["path"] for row in rows] + scope.get("paths", []):
        relative_path(name)
    if len({row["path"] for row in rows}) != len(rows):
        raise ValueError(f"Duplicate test paths in report: {path}")
    failed = {row["path"] for row in rows if row["status"] != "passed"}
    failed.update(set(scope.get("paths", [])) - {row["path"] for row in rows})
    return failed


def check_mapping(value, allowed: set[str], label: str) -> dict:
    if not isinstance(value, dict):
        raise ValueError(f"{label} must be a JSON object")
    unknown = set(value) - allowed
    if unknown:
        raise ValueError(f"Unknown {label} setting(s): {', '.join(sorted(unknown))}")
    return value


def discover(project: Path, config: dict) -> list[Test]:
    check_mapping(config, {"roots", "defaults", "tests"}, "suite")
    overrides = config.get("tests", {})
    defaults = config.get("defaults", {})
    check_mapping(defaults, {"timeout_seconds", "jobs"}, "defaults")
    if not isinstance(overrides, dict):
        raise ValueError("tests must be a JSON object keyed by project-relative paths")
    roots = config.get("roots", ["tests/validation", "tests/benchmarks"])
    if not isinstance(roots, list) or not roots:
        raise ValueError("roots must be a nonempty array of project-relative directories")
    worker_count(defaults.get("jobs", 4))
    paths = set()
    for root in roots:
        directory = project / relative_path(root)
        if not directory.is_dir():
            raise ValueError(f"Configured test root does not exist: {root}")
        if not directory.resolve().is_relative_to(project.resolve()):
            raise ValueError(f"Test root escapes the project: {root}")
        paths.update(p for p in directory.rglob("*") if p.is_file() and p.suffix in (".gd", ".py"))
    cases = []
    for path in sorted(paths):
        name = path.relative_to(project).as_posix()
        options = overrides.get(name, {})
        check_mapping(options, {"mode", "reason", "timeout_seconds", "serial", "editor_plugins"}, name)
        if not isinstance(options.get("serial", False), bool):
            raise ValueError(f"serial must be true or false: {name}")
        if not isinstance(options.get("editor_plugins", True), bool):
            raise ValueError(f"editor_plugins must be true or false: {name}")
        if not isinstance(options.get("mode", ""), str) or not isinstance(options.get("reason", ""), str):
            raise ValueError(f"mode and reason must be strings: {name}")
        mode = "unconfigured"
        entrypoint = name
        if path.name.startswith(("validate_", "test_")):
            if path.suffix == ".py":
                mode = "python"
            else:
                text = path.read_text()
                match = re.search(r"^extends\s+(\w+)\s*(?:#.*)?$", text, re.M)
                if re.search(r'^extends\s+[\"\'](?:res://tests/validation/)?test_case\.gd[\"\']\s*(?:#.*)?$', text, re.M):
                    mode = "case"
                elif match and match.group(1) == "SceneTree":
                    mode = "script"
                elif path.with_suffix(".tscn").is_file():
                    mode = "scene"
                    entrypoint = path.with_suffix(".tscn").relative_to(project).as_posix()
        mode = options.get("mode", mode)
        reason = options.get("reason", "")
        if "editor_plugins" in options and mode != "editor":
            raise ValueError(f"editor_plugins requires editor mode: {name}")
        if mode not in RUNNABLE | {"helper", "manual", "unconfigured"}:
            raise ValueError(f"Unknown launch mode for {name}: {mode}")
        if mode in ("helper", "manual") and not reason:
            raise ValueError(f"Non-test entry needs a reason: {name}")
        timeout = positive_seconds(options.get("timeout_seconds", defaults.get("timeout_seconds", DEFAULT_TIMEOUT)))
        test = Test(name, mode, entrypoint, timeout, options.get("serial", False), reason,
                    options.get("editor_plugins", True))
        cases.append(replace(test, serial=True) if test.benchmark else test)
    unknown = set(overrides) - {case.path for case in cases}
    if unknown:
        raise ValueError("Suite settings refer to missing tests: " + ", ".join(sorted(unknown)))
    return cases


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project", type=Path, default=PROJECT, help="Godot project root (defaults to this checkout)")
    parser.add_argument("--list", action="store_true", help="List tests and launch modes without running anything")
    parser.add_argument("--benchmarks", action="store_true", help="Run only tests/benchmarks (excluded from normal suite runs)")
    colors = parser.add_mutually_exclusive_group()
    colors.add_argument("--no-color", action="store_true", help="Use plain terminal output")
    colors.add_argument("--color", action="store_true", help="Force colored output (automatic in a terminal)")
    parser.add_argument("--report-dir", type=Path, help="Save a run in a separate empty directory instead of replacing this suite's latest report")
    parser.add_argument("--timeout", type=positive_seconds, help="Override every selected test's wall-clock timeout (seconds)")
    parser.add_argument("--filter", action="append", default=[], metavar="TEXT", help="Run paths containing TEXT (repeat to select more)")
    parser.add_argument("--jobs", type=worker_count, help="Parallel workers; timing-sensitive tests still run alone (1–16)")
    parser.add_argument("--godot", default=os.environ.get("GODOT", "godot"), help="Godot executable path/name (or set GODOT)")
    parser.add_argument("--rerun-failed", nargs="?", const="", metavar="REPORT", help="Rerun unsuccessful tests from a report; defaults to the latest run")
    args = parser.parse_args()
    project = args.project.resolve()
    console = Console(args.color or (not args.no_color and sys.stdout.isatty() and "NO_COLOR" not in os.environ and os.environ.get("TERM") != "dumb"))
    try:
        if not (project / "project.godot").is_file():
            raise ValueError(f"No project.godot in {project}")
        config_file = project / CONFIG_PATH
        config = json.loads(config_file.read_text()) if config_file.exists() else {}
        all_cases = discover(project, config)
        if not all_cases:
            raise ValueError("No validators discovered; check tests/validation/suite.json")
        cases = [case for case in all_cases if case.benchmark == args.benchmarks]
        if any(not pattern for pattern in args.filter):
            raise ValueError("A test filter cannot be empty")
        selected = [case for case in cases if not args.filter or any(pattern.lower() in case.path.lower() for pattern in args.filter)]
        if args.rerun_failed is not None:
            failed = previous_failures(project, args.rerun_failed, benchmarks=args.benchmarks)
            unknown = failed - {case.path for case in all_cases}
            if unknown:
                raise ValueError("Previous tests are no longer discoverable: " + ", ".join(sorted(unknown)))
            selected = [case for case in selected if case.path in failed]
        if not selected:
            raise ValueError("No tests match the selection; nothing was run. Benchmarks require --benchmarks.")
        console.title(args.benchmarks)
        if args.list:
            for case in selected:
                print(f"  {case.mode:12} {case.path}" + (f" — {case.reason}" if case.reason else ""))
            return 2 if any(case.mode == "unconfigured" for case in selected) else 0
        tests = [case for case in selected if case.mode not in ("helper", "manual")]
        total = sum(case.mode not in ("helper", "manual") for case in cases)
        scope = {"suite": "benchmarks" if args.benchmarks else "tests",
                 "discovered": total, "selected": len(tests),
                 "full_suite": not args.benchmarks and len(tests) == total,
                 "paths": [case.path for case in tests],
                 "non_tests": [{"path": case.path, "mode": case.mode, "reason": case.reason}
                               for case in cases if case.mode in ("helper", "manual")]}
        label = "BENCHMARKS" if args.benchmarks else ("FULL VALIDATION" if scope["full_suite"] else "FILTERED VALIDATION")
        unit = "benchmarks" if args.benchmarks else "validators"
        print(f"  {label}  ·  {len(tests)} of {total} {unit}  ·  isolated project and user data")
        if args.timeout is not None:
            tests = [replace(case, timeout=args.timeout) for case in tests]
        if not tests:
            raise ValueError("No automated tests selected")
        latest = report_root(project, args.benchmarks) / "latest"
        destination = (args.report_dir or latest).absolute()
        jobs = args.jobs if args.jobs is not None else worker_count(config.get("defaults", {}).get("jobs", 4))
        godot = shutil.which(args.godot)
        if godot is None and any(test.mode in GODOT_MODES for test in tests):
            raise ValueError(f"Godot not found: {args.godot}. Set --godot or GODOT; no tests were run.")
        with report_output(destination, replace_existing=destination == latest):
            return run_suite(project, tests, destination, str(Path(godot).resolve()) if godot else args.godot, scope, jobs, console)
    except (ValueError, OSError) as error:
        print(f"Test runner: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main())
