#!/usr/bin/env python3
"""Behavior tests for the repository test runner; no Godot install required."""
from __future__ import annotations

from concurrent.futures import ThreadPoolExecutor
import hashlib
import importlib.util
import json
import os
from pathlib import Path
import re
import shutil
import signal
import subprocess
import sys
import tempfile
from threading import Event
import time
import unittest
from unittest import mock

RUNNER = Path(__file__).resolve().parents[1] / "run_validation.py"
SPEC = importlib.util.spec_from_file_location("mygame_test_runner", RUNNER)
assert SPEC is not None and SPEC.loader is not None
runner = importlib.util.module_from_spec(SPEC)
sys.modules[SPEC.name] = runner
SPEC.loader.exec_module(runner)


class RunnerCliTests(unittest.TestCase):
    def setUp(self):
        self.temporary = tempfile.TemporaryDirectory(prefix="mygame-runner-test-")
        self.addCleanup(self.temporary.cleanup)
        self.project = Path(self.temporary.name) / "project with spaces"
        self.project.mkdir()
        (self.project / "project.godot").write_text('[application]\nconfig/name="Runner fixture"\n')
        self.validation = self.project / "tests/validation"
        self.validation.mkdir(parents=True)
        (self.project / "tests/benchmarks").mkdir()
        config = self.project / "tests/validation/suite.json"
        config.write_text(json.dumps({"roots": ["tests/validation", "tests/benchmarks"]}))

    def invoke(self, *arguments, timeout=20):
        return subprocess.run(
            [sys.executable, str(RUNNER), "--project", str(self.project),
             *([] if "--color" in arguments else ["--no-color"]), *arguments],
            cwd=self.temporary.name, text=True, capture_output=True, timeout=timeout,
        )

    def test_root_runner_defaults_to_its_own_project_without_setup(self):
        root_runner = self.project / "tests/run_validation.py"
        shutil.copy2(RUNNER, root_runner)
        tests = self.validation
        tests.mkdir(exist_ok=True)
        (tests / "validate_root.py").write_text("print('ROOT_OK')\n")
        # Omit roots to exercise default discovery, not a fixture override.
        (self.project / "tests/validation/suite.json").write_text("{}\n")
        result = subprocess.run(
            [sys.executable, str(root_runner), "--list", "--no-color"],
            cwd=self.temporary.name, text=True, capture_output=True, timeout=10,
        )
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        self.assertIn("tests/validation/validate_root.py", result.stdout)
        self.assertFalse((self.project / ".test-results/validation").exists())

    def test_default_report_replaces_one_fixed_directory_and_reruns_failures(self):
        bad = self.validation / "validate_bad.py"
        bad.write_text("print('FIRST_FAILURE')\nraise SystemExit(1)\n")
        (self.validation / "validate_good.py").write_text("print('GOOD_OK')\n")
        destination = self.project / ".test-results/validation/latest"
        first = self.invoke()
        self.assertEqual(first.returncode, 1, first.stdout + first.stderr)
        self.assertTrue((destination / "index.html").is_file(), "Default report needs a stable location")
        original = json.loads((destination / "report.json").read_text())
        self.assertEqual(original["counts"], {"failed": 1, "passed": 1})
        old_good = next(row for row in original["results"] if row["status"] == "passed")
        (destination / "stale-artifact.txt").write_text("must not accumulate")
        bad.write_text("print('NOW_OK')\n")
        second = self.invoke("--rerun-failed")
        self.assertEqual(second.returncode, 0, second.stdout + second.stderr)
        report = json.loads((destination / "report.json").read_text())
        self.assertEqual(report["counts"], {"passed": 1})
        self.assertEqual(report["scope"]["paths"], ["tests/validation/validate_bad.py"])
        self.assertFalse(report["scope"]["full_suite"])
        self.assertFalse((destination / "stale-artifact.txt").exists())
        self.assertFalse((destination / old_good["log"]).exists(), "Previous logs must not accumulate")
        self.assertEqual(len((destination / "results.jsonl").read_text().splitlines()), 1)
        self.assertIn("NOW_OK", (destination / report["results"][0]["log"]).read_text())
        self.assertEqual([p.name for p in destination.parent.iterdir() if p.is_dir()], ["latest"])
        self.assertIn(str(destination / "index.html"), second.stdout)

    def test_default_output_refuses_unowned_or_symlinked_directories(self):
        (self.validation / "validate_example.py").write_text("print('OK')\n")
        destination = self.project / ".test-results/validation/latest"
        destination.mkdir(parents=True)
        sentinel = destination / "keep.txt"
        sentinel.write_text("not generated by the runner")
        result = self.invoke()
        self.assertEqual(result.returncode, 2, result.stdout + result.stderr)
        self.assertEqual(sentinel.read_text(), "not generated by the runner")
        self.assertEqual(list(destination.iterdir()), [sentinel])
        shutil.rmtree(destination)
        outside = Path(self.temporary.name) / "outside"
        outside.mkdir()
        sentinel = outside / "keep.txt"
        sentinel.write_text("outside the report directory")
        destination.symlink_to(outside, target_is_directory=True)
        result = self.invoke()
        self.assertEqual(result.returncode, 2, result.stdout + result.stderr)
        self.assertEqual(sentinel.read_text(), "outside the report directory")

    def test_default_output_cannot_replace_an_active_run(self):
        ready = Path(self.temporary.name) / "ready"
        release = Path(self.temporary.name) / "release"
        (self.validation / "validate_wait.py").write_text(
            "from pathlib import Path\nimport time\n"
            f"Path({str(ready)!r}).touch()\n"
            f"while not Path({str(release)!r}).exists():\n    time.sleep(0.01)\n"
            "print('COMPLETED_OK')\n"
        )
        destination = self.project / ".test-results/validation/latest"
        process = subprocess.Popen(
            [sys.executable, str(RUNNER), "--project", str(self.project), "--no-color"],
            stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True,
        )
        try:
            deadline = time.monotonic() + 5
            while not ready.exists() and time.monotonic() < deadline:
                time.sleep(0.02)
            self.assertTrue(ready.exists(), "First run did not reach its validator")
            self.assertTrue((destination / "report.json").is_file(), "Active report is not at its fixed path")
            before = (destination / "report.json").read_bytes()
            second = self.invoke(timeout=5)
            self.assertEqual(second.returncode, 2, second.stdout + second.stderr)
            self.assertIn("already writing", second.stderr)
            self.assertEqual((destination / "report.json").read_bytes(), before)
            release.touch()
            stdout, stderr = process.communicate(timeout=5)
            self.assertEqual(process.returncode, 0, stdout + stderr)
            self.assertTrue(json.loads((destination / "report.json").read_text())["complete"])
        finally:
            release.touch()
            if process.poll() is None:
                process.send_signal(signal.SIGTERM)
            process.communicate(timeout=6)

    def test_report_artifacts_are_git_ignored_at_default_and_custom_paths(self):
        subprocess.run(["git", "init", "-q", str(self.project)], check=True)
        (self.validation / "validate_example.py").write_text("print('OK')\n")
        custom = self.project / "reports/custom"
        for arguments, destination in (((), self.project / ".test-results/validation/latest"),
                                       (("--report-dir", str(custom)), custom)):
            with self.subTest(destination=destination):
                result = self.invoke(*arguments)
                self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
                artifacts = [p.relative_to(self.project).as_posix() for base in
                             (self.project / ".test-results/validation", custom) if base.exists()
                             for p in base.rglob("*") if p.is_file()]
                check = subprocess.run(["git", "check-ignore", "--stdin"], cwd=self.project,
                                       input="\n".join(artifacts) + "\n", text=True, capture_output=True)
                self.assertEqual(set(check.stdout.splitlines()), set(artifacts), check.stderr)
                self.assertNotEqual(subprocess.run(["git", "check-ignore", "tests/validation/validate_example.py"],
                                                   cwd=self.project, capture_output=True).returncode, 0)
        before = (custom / "report.json").read_bytes()
        repeated = self.invoke("--report-dir", str(custom))
        self.assertEqual(repeated.returncode, 2, "Explicit saved evidence must not be overwritten")
        self.assertEqual((custom / "report.json").read_bytes(), before)

    def test_snapshot_can_run_nested_root_runner_selfchecks(self):
        shutil.copy2(RUNNER, self.project / "tests/run_validation.py")
        shutil.copy2(RUNNER.parent / "validation/report_template.html", self.validation / "report_template.html")
        shutil.copy2(__file__, self.validation / "test_run_tests.py")
        (self.validation / "validate_nested.py").write_text(
            "import json, subprocess, sys\nfrom pathlib import Path\n"
            "assert json.loads(Path('tests/validation/suite.json').read_text())['roots'] == ['tests/validation', 'tests/benchmarks']\n"
            "subprocess.run([sys.executable, 'tests/validation/test_run_tests.py',\n"
            "    'RunnerCliTests.test_root_runner_defaults_to_its_own_project_without_setup',\n"
            "    'RunnerCliTests.test_runs_and_reports_python_validator_in_an_isolated_copy'], check=True)\n"
            "print('NESTED_SELFCHECKS_OK')\n"
        )
        destination = Path(self.temporary.name) / "results"
        result = self.invoke("--filter", "validate_nested.py", "--godot", "no-godot-installed",
                             "--report-dir", str(destination))
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        report = json.loads((destination / "report.json").read_text())
        self.assertEqual(report["counts"], {"passed": 1})
        self.assertIn("NESTED_SELFCHECKS_OK", (destination / report["results"][0]["log"]).read_text())

    def test_snapshot_excludes_local_agent_json_when_copying_suite_config(self):
        local_configs = (".mcp.json", "opencode.json", "tui.json")
        for name in local_configs:
            (self.project / name).write_text('{"fixture": "local-only"}\n')
        snapshot = Path(self.temporary.name) / "snapshot"
        runner.copy_project(self.project, snapshot)
        self.assertTrue((snapshot / "tests/validation/suite.json").is_file())
        for name in local_configs:
            self.assertFalse((snapshot / name).exists(), f"Local agent configuration was copied: {name}")

    def test_list_discovers_nested_validators_without_running_godot(self):
        nested = self.validation / "nested"
        nested.mkdir()
        (nested / "validate_example.gd").write_text("extends SceneTree\n")
        result = self.invoke("--list")
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertIn("validate_example", result.stdout)
        self.assertIn("script", result.stdout)
        self.assertFalse((self.project / ".test-results/validation").exists())

    def test_default_suite_excludes_benchmarks_even_with_filters_or_reruns(self):
        regular_path = "tests/validation/validate_regular.py"
        benchmark_path = "tests/benchmarks/combat/validate_metric.py"
        (self.project / regular_path).write_text("print('REGULAR_OK')\n")
        benchmark = self.project / benchmark_path
        benchmark.parent.mkdir(parents=True)
        marker = Path(self.temporary.name) / "benchmark-ran"
        benchmark.write_text(
            "from pathlib import Path\n"
            f"Path({str(marker)!r}).touch()\n"
            "raise SystemExit(1)\n"
        )
        for arguments in ((), ("--filter", "validate_")):
            with self.subTest(arguments=arguments):
                result = self.invoke(*arguments)
                self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
                report = json.loads((self.project / ".test-results/validation/latest/report.json").read_text())
                self.assertEqual(report["scope"]["paths"], [regular_path])
                self.assertEqual(report["scope"]["discovered"], 1)
                self.assertTrue(report["scope"]["full_suite"])
                self.assertFalse(marker.exists(), "Normal suite launched a benchmark")
        listed = self.invoke("--list")
        self.assertEqual(listed.returncode, 0, listed.stderr)
        self.assertNotIn(benchmark_path, listed.stdout)
        previous = Path(self.temporary.name) / "mixed-failures.json"
        previous.write_text(json.dumps({"results": [
            {"path": regular_path, "status": "failed"},
            {"path": benchmark_path, "status": "failed"},
        ]}))
        result = self.invoke("--rerun-failed", str(previous))
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        report = json.loads((self.project / ".test-results/validation/latest/report.json").read_text())
        self.assertEqual(report["scope"]["paths"], [regular_path])
        focused = self.invoke("--filter", benchmark_path)
        self.assertEqual(focused.returncode, 2, focused.stdout + focused.stderr)
        self.assertIn("--benchmarks", focused.stderr)
        self.assertFalse(marker.exists(), "Filter/rerun silently opted into benchmarks")

    def test_benchmark_mode_runs_only_benchmarks_serially(self):
        (self.validation / "validate_regular.py").write_text("raise SystemExit('must not run')\n")
        benchmarks = self.project / "tests/benchmarks"
        paths = [f"tests/benchmarks/validate_{name}.py" for name in ("first", "second")]
        for path in paths:
            (self.project / path).write_text("import time\ntime.sleep(0.1)\nprint('METRIC_OK')\n")
        listed = self.invoke("--benchmarks", "--list")
        self.assertEqual(listed.returncode, 0, listed.stdout + listed.stderr)
        for path in paths:
            self.assertIn(path, listed.stdout)
        self.assertNotIn("tests/validation/validate_regular.py", listed.stdout)
        self.assertFalse((self.project / ".test-results").exists(), "Listing must not create reports")
        destination = Path(self.temporary.name) / "benchmark-results"
        result = self.invoke("--benchmarks", "--jobs", "4", "--report-dir", str(destination))
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        report = json.loads((destination / "report.json").read_text())
        self.assertEqual(report["scope"]["paths"], paths)
        self.assertEqual(report["scope"]["suite"], "benchmarks")
        self.assertEqual(report["scope"]["discovered"], 2)
        self.assertFalse(report["scope"]["full_suite"], "A benchmark run is never feature-suite acceptance")
        self.assertEqual(report["counts"], {"passed": 2})
        first, second = report["results"]
        self.assertTrue(all(row["serial"] for row in report["results"]))
        self.assertGreaterEqual(second["started_monotonic"], first["finished_monotonic"])
        self.assertTrue(all("--benchmarks" in row["rerun_command"] for row in report["results"]))
        self.assertIn("BENCHMARKS", result.stdout)
        self.assertNotIn("FULL SUITE", result.stdout)
        focused = Path(self.temporary.name) / "focused-benchmark"
        result = self.invoke("--benchmarks", "--filter", "second", "--report-dir", str(focused))
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        report = json.loads((focused / "report.json").read_text())
        self.assertEqual(report["scope"]["paths"], [paths[1]])
        self.assertEqual(report["scope"]["discovered"], 2)

    def test_benchmark_reports_and_failure_reruns_stay_separate_from_the_suite(self):
        subprocess.run(["git", "init", "-q", str(self.project)], check=True)
        regular = self.validation / "validate_regular.py"
        regular.write_text("raise SystemExit(1)\n")
        self.assertEqual(self.invoke().returncode, 1)
        suite_report = self.project / ".test-results/validation/latest/report.json"
        suite_pointer = self.project / ".test-results/validation/latest.json"
        previous_suite = {path: path.read_bytes() for path in (suite_report, suite_pointer)}
        regular.write_text("print('REGULAR_OK')\n")
        benchmarks = self.project / "tests/benchmarks"
        bad = benchmarks / "validate_bad.py"
        bad.write_text("print('ERROR: measured performance miss')\n")
        (benchmarks / "validate_good.py").write_text("print('METRIC_OK')\n")
        first = self.invoke("--benchmarks")
        self.assertEqual(first.returncode, 1, first.stdout + first.stderr)
        destination = self.project / ".test-results/benchmarks/latest"
        self.assertTrue((destination / "index.html").is_file(), "Benchmark output must be hidden and separate")
        report = json.loads((destination / "report.json").read_text())
        self.assertEqual(report["counts"], {"failed": 1, "passed": 1})
        failed = next(row for row in report["results"] if row["status"] == "failed")
        self.assertEqual(failed["exit_code"], 0, "Benchmarks still fail on errors despite zero exit")
        self.assertEqual(failed["errors"], ["ERROR: measured performance miss"])
        for path, content in previous_suite.items():
            self.assertEqual(path.read_bytes(), content, "Benchmark run replaced the feature-suite report/pointer")
        (destination / "stale-artifact.txt").touch()
        bad.write_text("print('MEASURED_OK')\n")
        rerun = self.invoke("--benchmarks", "--rerun-failed")
        self.assertEqual(rerun.returncode, 0, rerun.stdout + rerun.stderr)
        report = json.loads((destination / "report.json").read_text())
        self.assertEqual(report["scope"]["paths"], ["tests/benchmarks/validate_bad.py"])
        self.assertEqual(report["counts"], {"passed": 1})
        self.assertFalse((destination / "stale-artifact.txt").exists())
        self.assertEqual([path.name for path in destination.parent.iterdir() if path.is_dir()], ["latest"])
        self.assertTrue((destination.parent / ".gdignore").is_file())
        self.assertTrue((destination / ".gdignore").is_file())
        artifacts = [path.relative_to(self.project).as_posix()
                     for path in destination.parent.rglob("*") if path.is_file()]
        ignored = subprocess.run(["git", "check-ignore", "--stdin"], cwd=self.project,
                                 input="\n".join(artifacts) + "\n", text=True, capture_output=True)
        self.assertEqual(set(ignored.stdout.splitlines()), set(artifacts), ignored.stderr)
        benchmark_report = (destination / "report.json").read_bytes()
        regular_rerun = self.invoke("--rerun-failed")
        self.assertEqual(regular_rerun.returncode, 0, regular_rerun.stdout + regular_rerun.stderr)
        self.assertEqual(json.loads(suite_report.read_text())["scope"]["paths"], ["tests/validation/validate_regular.py"])
        self.assertEqual((destination / "report.json").read_bytes(), benchmark_report)

    def test_case_uses_normal_scene_startup_before_loading_the_test(self):
        path = "tests/validation/validate_autoload.gd"
        (self.project / path).write_text('extends "res://tests/validation/test_case.gd"\n')
        cases = runner.discover(self.project, {"roots": ["tests/validation", "tests/benchmarks"]})
        self.assertEqual(len(cases), 1)
        self.assertEqual(cases[0].mode, "case")
        command = runner.command_for(cases[0], self.project, Path(self.temporary.name), "godot")
        self.assertNotIn("--script", command)
        self.assertEqual(command[-4:], ["--scene", "res://tests/validation/test_host.tscn", "--", "res://" + path])

    def test_runs_and_reports_python_validator_in_an_isolated_copy(self):
        (self.validation / "validate_example.py").write_text(
            "from pathlib import Path\n"
            "Path('generated.txt').write_text('test output')\n"
            "print('EXAMPLE_OK')\n"
        )
        destination = Path(self.temporary.name) / "results"
        result = self.invoke("--report-dir", str(destination))
        self.assertEqual(result.returncode, 0, result.stderr)
        report = json.loads((destination / "report.json").read_text())
        self.assertEqual(report["counts"]["passed"], 1)
        self.assertEqual(report["results"][0]["status"], "passed")
        self.assertIn("EXAMPLE_OK", (destination / report["results"][0]["log"]).read_text())
        self.assertFalse((self.project / "generated.txt").exists())

    def test_error_output_fails_even_with_zero_exit_and_keeps_running(self):
        (self.validation / "validate_bad.py").write_text(
            "print('\\x1b[31mSCRIPT ERROR: deliberately tested failure\\x1b[0m')\n"
            "print('FALSE_SUCCESS_OK')\n"
        )
        (self.validation / "validate_good.py").write_text("print('GOOD_OK')\n")
        destination = Path(self.temporary.name) / "results"
        result = self.invoke("--report-dir", str(destination))
        self.assertEqual(result.returncode, 1, result.stderr)
        report = json.loads((destination / "report.json").read_text())
        self.assertEqual(report["counts"], {"failed": 1, "passed": 1})
        bad = next(row for row in report["results"] if row["status"] == "failed")
        self.assertEqual(bad["exit_code"], 0)
        self.assertIn("deliberately tested failure", bad["errors"][0])

    def test_timeout_is_reported_and_descendants_are_stopped(self):
        (self.validation / "validate_slow.py").write_text(
            "import subprocess, sys, time\n"
            "child = subprocess.Popen([sys.executable, '-c', 'import time; time.sleep(30)'])\n"
            "print('CHILD_PID', child.pid, flush=True)\n"
            "time.sleep(30)\n"
        )
        destination = Path(self.temporary.name) / "results"
        result = self.invoke("--timeout", "0.3", "--report-dir", str(destination))
        self.assertEqual(result.returncode, 1, result.stderr)
        report = json.loads((destination / "report.json").read_text())
        self.assertEqual(report["counts"], {"timeout": 1})
        log = (destination / report["results"][0]["log"]).read_text()
        child_pid = int(log.split("CHILD_PID ")[1].splitlines()[0])
        if sys.platform.startswith("linux"):
            state = Path(f"/proc/{child_pid}/stat")
            for _ in range(20):
                if not state.exists() or state.read_text().split()[2] == "Z":
                    break
                time.sleep(0.05)
            else:
                os.kill(child_pid, 9)
                self.fail("Timeout left a live descendant behind")

    def test_filter_is_explicitly_reported_as_a_partial_run(self):
        for name in ("inventory", "farming"):
            (self.validation / f"validate_{name}.py").write_text("print('OK')\n")
        destination = Path(self.temporary.name) / "results"
        result = self.invoke("--filter", "inventory", "--report-dir", str(destination))
        self.assertEqual(result.returncode, 0, result.stderr)
        report = json.loads((destination / "report.json").read_text())
        self.assertEqual(report["scope"]["discovered"], 2)
        self.assertEqual(report["scope"]["selected"], 1)
        self.assertFalse(report["scope"]["full_suite"])
        self.assertEqual(report["results"][0]["path"], "tests/validation/validate_inventory.py")
        self.assertIn("FILTERED", result.stdout)

    def test_parallel_tests_use_separate_copies_and_serial_tests_run_alone(self):
        for name in ("first", "second", "serial"):
            (self.validation / f"validate_{name}.py").write_text(
                "import time\nfrom pathlib import Path\n"
                "print(Path.cwd())\ntime.sleep(0.25)\nprint('OK')\n"
            )
        (self.project / "tests/validation/suite.json").write_text(json.dumps({
            "roots": ["tests/validation", "tests/benchmarks"],
            "tests": {"tests/validation/validate_serial.py": {"serial": True}},
        }))
        destination = Path(self.temporary.name) / "results"
        result = self.invoke("--jobs", "2", "--report-dir", str(destination))
        self.assertEqual(result.returncode, 0, result.stderr)
        report = json.loads((destination / "report.json").read_text())
        rows = {Path(row["path"]).stem: row for row in report["results"]}
        first, second, serial = (rows["validate_" + name] for name in ("first", "second", "serial"))
        self.assertLess(max(first["started_monotonic"], second["started_monotonic"]),
                        min(first["finished_monotonic"], second["finished_monotonic"]))
        self.assertGreaterEqual(serial["started_monotonic"],
                                max(first["finished_monotonic"], second["finished_monotonic"]))
        roots = [(destination / row["log"]).read_text().splitlines()[0] for row in (first, second)]
        self.assertNotEqual(*roots)

    @unittest.skipUnless(os.name == "posix", "POSIX process-group cancellation")
    def test_ctrl_c_saves_an_incomplete_report_and_cancels_pending_tests(self):
        for name in ("first", "second"):
            (self.validation / f"validate_{name}.py").write_text(
                "import os, time\nprint('READY', os.getpid(), flush=True)\ntime.sleep(30)\n"
            )
        destination = Path(self.temporary.name) / "results"
        process = subprocess.Popen(
            [sys.executable, str(RUNNER), "--project", str(self.project), "--jobs", "1",
             "--timeout", "2", "--report-dir", str(destination), "--no-color"],
            stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True,
        )
        try:
            for _ in range(60):
                logs = list(destination.glob("logs/*/output.log"))
                if logs and "READY" in logs[0].read_text():
                    break
                time.sleep(0.05)
            else:
                self.fail("Fixture never started")
            process.send_signal(signal.SIGINT)
            stdout, stderr = process.communicate(timeout=6)
            self.assertEqual(process.returncode, 130, stdout + stderr)
            self.assertTrue((destination / "report.json").exists(), "Cancellation lost the report")
            report = json.loads((destination / "report.json").read_text())
            self.assertFalse(report["complete"])
            self.assertEqual(report["counts"], {"interrupted": 2})
            self.assertEqual(len(report["results"]), 2)
        finally:
            if process.poll() is None:
                process.kill()
                process.communicate()
            for log in destination.glob("logs/*/output.log"):
                if "READY " in log.read_text():
                    pid = int(log.read_text().split("READY ")[1].splitlines()[0])
                    try:
                        os.killpg(pid, signal.SIGKILL)
                    except ProcessLookupError:
                        pass

    def test_dispatches_script_scene_and_editor_entrypoints(self):
        for name, base in (("script", "SceneTree"), ("scene", "Node"), ("editor", "SceneTree")):
            (self.validation / f"validate_{name}.gd").write_text(f"extends {base}\n")
        (self.validation / "validate_scene.tscn").write_text('[gd_scene format=3]\n[node name="Fixture" type="Node"]\n')
        (self.project / "tests/validation/suite.json").write_text(json.dumps({
            "roots": ["tests/validation", "tests/benchmarks"],
            "tests": {"tests/validation/validate_editor.gd": {"mode": "editor"}},
        }))
        fake_godot = Path(self.temporary.name) / "fake-godot"
        fake_godot.write_text(f"#!{sys.executable}\nimport json,sys\nprint(json.dumps(sys.argv[1:]))\n")
        fake_godot.chmod(0o755)
        destination = Path(self.temporary.name) / "results"
        result = self.invoke("--godot", str(fake_godot), "--report-dir", str(destination))
        self.assertEqual(result.returncode, 0, result.stderr)
        report = json.loads((destination / "report.json").read_text())
        for row in report["results"]:
            command = json.loads((destination / row["log"]).read_text())
            self.assertIn("--headless", command)
            if row["mode"] == "scene":
                self.assertIn("--scene", command)
                self.assertEqual(command[-1], "res://tests/validation/validate_scene.tscn")
                self.assertNotIn("--script", command)
            else:
                self.assertIn("--script", command)
                self.assertEqual("--editor" in command, row["mode"] == "editor")

    def test_editor_node_scene_keeps_the_native_editor_main_loop(self):
        path = "tests/validation/validate_editor_scene.gd"
        (self.project / path).write_text("@tool\nextends Node\n")
        scene = "tests/validation/validate_editor_scene.tscn"
        (self.project / scene).write_text('[gd_scene format=3]\n[node name="Fixture" type="Node"]\n')
        config = {"tests": {path: {"mode": "editor"}}}
        cases = runner.discover(self.project, config)
        self.assertEqual(len(cases), 1)
        self.assertEqual((cases[0].path, cases[0].mode, cases[0].entrypoint),
                         (path, "editor", scene))
        command = runner.command_for(cases[0], self.project, Path(self.temporary.name), "godot")
        self.assertIn("--editor", command)
        self.assertNotIn("--script", command, "Editor scenes must not replace the native editor main loop")
        self.assertEqual(command[-2:], ["--scene", "res://" + scene])

    def test_editor_plugin_isolation_precedes_launch_and_restores_worker(self):
        original = (self.project / "project.godot").read_bytes() + (
            b'\n[editor_plugins]\nenabled=PackedStringArray("res://addons/fixture/plugin.cfg")\n'
        )
        (self.project / "project.godot").write_bytes(original)
        for name in ("a_isolated", "b_regular"):
            (self.validation / f"validate_{name}.gd").write_text("@tool\nextends Node\n")
            (self.validation / f"validate_{name}.tscn").write_text(
                '[gd_scene format=3]\n[node name="Fixture" type="Node"]\n'
            )
        (self.project / "tests/validation/suite.json").write_text(json.dumps({"tests": {
            "tests/validation/validate_a_isolated.gd": {"mode": "editor", "editor_plugins": False},
            "tests/validation/validate_b_regular.gd": {"mode": "editor"},
        }}))
        fake_godot = Path(self.temporary.name) / "fake-editor"
        fake_godot.write_text(
            f"#!{sys.executable}\nimport configparser, hashlib, json, sys\nfrom pathlib import Path\n"
            "settings = configparser.RawConfigParser(strict=False)\n"
            "settings.read('project.godot')\n"
            "print(json.dumps({'plugins': settings.get('editor_plugins', 'enabled'),\n"
            "    'hash': hashlib.sha256(Path('project.godot').read_bytes()).hexdigest(),\n"
            "    'project': str(Path.cwd())}))\n"
            "if any('validate_a_isolated.tscn' in arg for arg in sys.argv):\n"
            "    print('ERROR: deliberate fixture error must still fail')\n"
        )
        fake_godot.chmod(0o755)
        destination = Path(self.temporary.name) / "results"
        result = self.invoke("--godot", str(fake_godot), "--jobs", "1", "--report-dir", str(destination))
        self.assertEqual(result.returncode, 1, result.stdout + result.stderr)
        report = json.loads((destination / "report.json").read_text())
        self.assertEqual(report["counts"], {"failed": 1, "passed": 1})
        isolated, regular = report["results"]
        observed = [json.loads((destination / row["log"]).read_text().splitlines()[0])
                    for row in (isolated, regular)]
        self.assertEqual(observed[0]["plugins"], "PackedStringArray()", "Isolation must precede editor startup")
        self.assertEqual(observed[0]["project"], observed[1]["project"], "Exercise actual worker reuse")
        self.assertEqual(observed[1]["hash"], hashlib.sha256(original).hexdigest(), "Restore exact settings after failure")
        self.assertFalse(isolated["editor_plugins"])
        self.assertTrue(regular["editor_plugins"])
        self.assertEqual(isolated["error_count"], 1, "Do not suppress editor errors")
        self.assertEqual((self.project / "project.godot").read_bytes(), original, "Never modify the live project")

    def test_editor_plugin_isolation_restores_after_timeout_cancel_and_launch_error(self):
        path = "tests/validation/validate_editor.gd"
        (self.project / path).write_text("extends SceneTree\n")
        original = (self.project / "project.godot").read_bytes()
        fake_godot = Path(self.temporary.name) / "slow-editor"
        fake_godot.write_text(f"#!{sys.executable}\nimport time\ntime.sleep(10)\n")
        fake_godot.chmod(0o755)
        for stop in ("timeout", "interrupted", "launch_error"):
            with self.subTest(stop=stop):
                cancelled = Event()
                if stop == "interrupted":
                    cancelled.set()
                executable = str(fake_godot) if stop != "launch_error" else str(fake_godot) + "-missing"
                test = runner.Test(path, "editor", path, timeout=0.1, editor_plugins=False)
                row = runner.run_test(test, self.project, Path(self.temporary.name) / stop,
                                      executable, cancelled)
                self.assertEqual(row["stop_reason"], stop)
                self.assertEqual((self.project / "project.godot").read_bytes(), original)

    def test_editor_plugin_option_requires_a_boolean_and_editor_mode(self):
        path = "tests/validation/validate_editor.gd"
        (self.project / path).write_text("extends SceneTree\n")
        for value in (None, [], 0, "false"):
            with self.subTest(value=value), self.assertRaisesRegex(ValueError, "editor_plugins must be true or false"):
                runner.discover(self.project, {"tests": {path: {"mode": "editor", "editor_plugins": value}}})
        with self.assertRaisesRegex(ValueError, "editor_plugins requires editor mode"):
            runner.discover(self.project, {"tests": {path: {"editor_plugins": False}}})
        cases = runner.discover(self.project, {"tests": {path: {"mode": "editor", "editor_plugins": True}}})
        self.assertTrue(cases[0].editor_plugins)

    def test_reruns_only_previous_failures_without_allowlisting_them(self):
        bad = self.validation / "validate_bad.py"
        bad.write_text("raise SystemExit(1)\n")
        (self.validation / "validate_good.py").write_text("print('OK')\n")
        first = Path(self.temporary.name) / "first"
        self.assertEqual(self.invoke("--report-dir", str(first)).returncode, 1)
        bad.write_text("print('NOW_OK')\n")
        second = Path(self.temporary.name) / "second"
        result = self.invoke("--rerun-failed", str(first / "report.json"), "--report-dir", str(second))
        self.assertEqual(result.returncode, 0, result.stderr)
        report = json.loads((second / "report.json").read_text())
        self.assertEqual(report["counts"], {"passed": 1})
        self.assertFalse(report["scope"]["full_suite"])
        self.assertEqual(report["results"][0]["path"], "tests/validation/validate_bad.py")

    def test_mistyped_suite_settings_do_not_silently_change_execution(self):
        (self.validation / "validate_example.py").write_text("print('OK')\n")
        config = self.project / "tests/validation/suite.json"
        bad_settings = [
            {"roots": ["tests/validation", "tests/benchmarks"], "defualts": {"jobs": 1}},
            {"roots": ["tests/validation", "tests/benchmarks"], "tests": {"tests/validation/validate_example.py": {"serial": "false"}}},
            {"roots": ["tests/validation", "tests/benchmarks"], "tests": {"tests/validation/validate_example.py": {"serially": True}}},
            {"roots": "tests"},
            {"roots": ["tests/validation", "misspelled"]},
            {"roots": ["tests/validation", "tests/benchmarks"], "defaults": {"timeout_seconds": None}},
            {"roots": ["tests/validation", "tests/benchmarks"], "defaults": {"timeout_seconds": True}},
        ]
        for settings in bad_settings:
            with self.subTest(settings=settings):
                config.write_text(json.dumps(settings))
                result = self.invoke("--list")
                self.assertEqual(result.returncode, 2, result.stdout + result.stderr)
                self.assertNotIn("Traceback", result.stderr)

    def test_unknown_files_are_blocked_but_documented_helpers_are_accounted_for(self):
        helper = self.validation / "fixture_cases.gd"
        helper.write_text("extends RefCounted\n")
        result = self.invoke("--list")
        self.assertEqual(result.returncode, 2)
        self.assertIn("unconfigured", result.stdout)
        (self.project / "tests/validation/suite.json").write_text(json.dumps({
            "roots": ["tests/validation", "tests/benchmarks"],
            "tests": {"tests/validation/fixture_cases.gd": {"mode": "helper", "reason": "Invoked by another validator"}},
        }))
        result = self.invoke("--list")
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertIn("Invoked by another validator", result.stdout)

    def test_repository_discovery_has_no_unconfigured_files(self):
        project = runner.PROJECT
        config = json.loads((project / "tests/validation/suite.json").read_text())
        cases = runner.discover(project, config)
        self.assertEqual([case.path for case in cases if case.mode == "unconfigured"], [])

    def test_invalid_inputs_fail_without_running_tests(self):
        (self.validation / "validate_example.py").write_text("print('OK')\n")
        for arguments in (("--filter", "does-not-exist"), ("--timeout", "nan"), ("--jobs", "0")):
            with self.subTest(arguments=arguments):
                result = self.invoke(*arguments)
                self.assertEqual(result.returncode, 2)
                self.assertFalse((self.project / ".test-results/validation").exists())

    def test_color_is_optional_and_plain_logs_remain_readable(self):
        (self.validation / "validate_example.py").write_text("print('OK')\n")
        result = self.invoke("--color", "--report-dir", str(Path(self.temporary.name) / "color"))
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertIn("\x1b[", result.stdout)
        result = self.invoke("--report-dir", str(Path(self.temporary.name) / "plain"))
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertNotIn("\x1b[", result.stdout)

    def test_named_failure_markers_fail_but_warnings_do_not(self):
        (self.validation / "validate_bad.py").write_text("print('FEATURE_FAILED count=1')\n")
        (self.validation / "validate_legacy.py").write_text("print('SLIDER_FEET_FAIL')\n")
        (self.validation / "validate_good.py").write_text("print('WARNING: fixture warning')\nprint('GOOD_OK')\n")
        destination = Path(self.temporary.name) / "results"
        result = self.invoke("--report-dir", str(destination))
        self.assertEqual(result.returncode, 1, result.stderr)
        report = json.loads((destination / "report.json").read_text())
        self.assertEqual(report["counts"], {"failed": 2, "passed": 1})


    def test_malformed_previous_report_is_an_input_error(self):
        (self.validation / "validate_example.py").write_text("print('OK')\n")
        previous = Path(self.temporary.name) / "previous.json"
        for data in ([], {"results": [{"path": [], "status": "failed"}]}, {"results": [], "scope": []}):
            with self.subTest(data=data):
                previous.write_text(json.dumps(data))
                result = self.invoke("--rerun-failed", str(previous))
                self.assertEqual(result.returncode, 2, result.stderr)
                self.assertNotIn("Traceback", result.stderr)


    def test_html_report_preserves_results_without_executing_log_markup(self):
        payload = 'ERROR: </script><script>window.untrusted_markup_ran = true</script>'
        (self.validation / "validate_markup.py").write_text(f"print({payload!r})\n")
        destination = Path(self.temporary.name) / "results"
        result = self.invoke("--report-dir", str(destination))
        self.assertEqual(result.returncode, 1, result.stderr)
        self.assertTrue((destination / "index.html").exists(), "No browsable report was generated")
        html = (destination / "index.html").read_text()
        self.assertNotIn(payload, html)
        self.assertNotIn("__TEST_REPORT_JSON__", html)
        embedded = re.search(r'<script type="application/json" id="report-data">(.*?)</script>', html, re.S)
        assert embedded is not None, "Report data block is missing"
        data = json.loads(embedded.group(1))
        self.assertEqual(data, json.loads((destination / "report.json").read_text()))
        self.assertEqual(data["results"][0]["errors"], [payload])
        self.assertEqual(data["runner_sha256"], hashlib.sha256(RUNNER.read_bytes()).hexdigest())


    def test_dated_audit_notes_do_not_override_runtime_results(self):
        test_path = "tests/validation/validate_example.py"
        (self.validation / "validate_example.py").write_text("print('OK')\n")
        (self.project / "tests/validation/audit.json").write_text(json.dumps({
            "reviewed_at": "fixture review date",
            "records": [{"path": test_path, "assessment": "coverage_gap", "summary": "Fixture audit note"}],
        }))
        destination = Path(self.temporary.name) / "results"
        result = self.invoke("--report-dir", str(destination))
        self.assertEqual(result.returncode, 0, result.stderr)
        report = json.loads((destination / "report.json").read_text())
        row = report["results"][0]
        self.assertIn("audit", row, "Dated audit note was not attached")
        self.assertEqual(row["status"], "passed")
        self.assertEqual(row["audit"]["assessment"], "coverage_gap")
        self.assertEqual(row["audit"]["reviewed_at"], "fixture review date")


    def test_finished_process_cannot_bypass_the_log_budget(self):
        path = "tests/validation/validate_noisy.py"
        (self.project / path).write_text(
            "import os\nblock = b'x' * (1024 * 1024 - 1) + b'\\n'\n"
            "for _ in range(65):\n    os.write(1, block)\n"
        )
        real_popen = subprocess.Popen

        def already_finished(*args, **kwargs):
            process = real_popen(*args, **kwargs)
            process.wait(timeout=5)
            return process

        # Deterministically exercise completion before the first monitor poll,
        # but use the real child and real output file, not fabricated results.
        with mock.patch.object(runner.subprocess, "Popen", side_effect=already_finished):
            row = runner.run_test(runner.Test(path, "python", path), self.project,
                                  Path(self.temporary.name) / "results", "unused", Event())
        self.assertEqual(row["exit_code"], 0)
        self.assertEqual(row["status"], "failed")
        self.assertEqual(row["stop_reason"], "log_limit")


    @unittest.skipUnless(sys.platform.startswith("linux"), "Linux process-state inspection")
    def test_cancellation_allows_nested_process_cleanup_after_leader_exits(self):
        marker = Path(self.temporary.name) / "leaf.pid"
        coordinator = self.validation / "coordinator.py"
        coordinator.write_text(
            "import os, signal, subprocess, sys, time\nfrom pathlib import Path\n"
            "stopping = False\n"
            "def stop(*_):\n    global stopping\n    stopping = True\n"
            "signal.signal(signal.SIGTERM, stop)\n"
            "child = subprocess.Popen([sys.executable, '-c', 'import time; time.sleep(30)'], start_new_session=True)\n"
            f"Path({str(marker)!r}).write_text(str(child.pid))\n"
            "while not stopping:\n    time.sleep(0.01)\n"
            "time.sleep(0.15)\n"
            "os.killpg(child.pid, signal.SIGTERM)\nchild.wait(timeout=2)\n"
        )
        path = "tests/validation/validate_outer.py"
        (self.project / path).write_text(
            "import subprocess, sys, time\n"
            f"subprocess.Popen([sys.executable, {str(coordinator)!r}])\n"
            "time.sleep(30)\n"
        )
        cancelled = Event()
        leaf_pid = None
        try:
            with ThreadPoolExecutor(max_workers=1) as pool:
                future = pool.submit(runner.run_test, runner.Test(path, "python", path, timeout=5),
                                     self.project, Path(self.temporary.name) / "results", "unused", cancelled)
                deadline = time.monotonic() + 3
                while not marker.exists() and time.monotonic() < deadline:
                    time.sleep(0.01)
                self.assertTrue(marker.exists(), "Nested child never became ready")
                leaf_pid = int(marker.read_text())
                cancelled.set()
                row = future.result(timeout=5)
            self.assertEqual(row["status"], "interrupted")
            state = Path(f"/proc/{leaf_pid}/stat")
            self.assertTrue(not state.exists() or state.read_text().split()[2] == "Z",
                            "Nested child remained alive after cancellation returned")
        finally:
            cancelled.set()
            if leaf_pid is not None:
                try:
                    os.killpg(leaf_pid, signal.SIGKILL)
                except ProcessLookupError:
                    pass


    def test_godot_ignore_files_exist_before_any_test_writes_artifacts(self):
        destination = self.project / "reports/custom-run"
        (self.validation / "validate_guard.py").write_text(
            "from pathlib import Path\n"
            f"assert Path({str(self.project / '.test-results/validation/.gdignore')!r}).is_file()\n"
            f"assert Path({str(destination / '.gdignore')!r}).is_file()\n"
            "print('GUARD_OK')\n"
        )
        result = self.invoke("--report-dir", str(destination))
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)


    def test_unit_scripts_are_outside_validation_discovery(self):
        unit = self.project / "tests/unit"
        unit.mkdir()
        (unit / "test_example.gd").write_text("extends GutTest\n")
        (self.validation / "validate_example.py").write_text("print('OK')\n")
        cases = runner.discover(self.project, {})
        self.assertEqual([case.path for case in cases],
                         ["tests/validation/validate_example.py"])
        result = self.invoke("--list")
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        self.assertNotIn("tests/unit", result.stdout)

    def test_canyon_measured_gate_has_serial_execution_metadata(self):
        project = runner.PROJECT
        cases = runner.discover(project, json.loads((project / runner.CONFIG_PATH).read_text()))
        canyon = next(test for test in cases if test.path == "tests/validation/validate_debug_time_skip_canyon.gd")
        self.assertTrue(canyon.serial, "The measured Canyon skip must not overlap other suite tests")


if __name__ == "__main__":
    unittest.main()
